# Generated by Django 3.0 on 2022-08-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0002_auto_20220814_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
