# Generated by Django 3.0 on 2022-08-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, verbose_name='user name'),
        ),
    ]
